#pragma once
#include "StartupParams.h"
#include <string>
#include <vector>
std::string Params::HostNethernetId;
std::string Params::FromNethernetId;
std::vector<std::string> Params::params;
std::string Params::ServerIP;
int Params::ServerPort;
std::string Params::MD5Token;
std::string Params::DisplayName;
std::string Params::UserID;
std::string Params::EngineVersion;
std::string Params::PatchVersion;
std::string Params::GameVersion;
std::string Params::AuthServerUrl;
std::string Params::NeteaseServerID;
std::string Params::Expand;
std::string Params::plugin_dir;
bool Params::g79;
bool Params::disout;
bool Params::logger;
bool Params::script_mcp;
bool Params::AutoAuthInput;
bool Params::RequestChunkRadius;
long long Params::PlayerEntityID;
int Params::launcher_port;